services:
  - type: web
    name: delegate-card-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DATABASE_URL
        fromDatabase:
          name: delegate-db
          property: connectionString

databases:
  - name: delegate-db
    databaseName: delegate_db
    user: delegate_user
    plan: free
